### ISSUE TITLE
[SEND HALP] ChatTriggers module not sending or server not detecting any data from plugin 

### ISSUE THREAD

**Issue by Bobu5** [matcool/skyblock-jacob#9]
title,  need help setting up the connection between ChatTriggers module and the skyblock-jacob Server

i have tried using 1 same `SECRET` for the .env and module's main.js

![image](https://user-images.githubusercontent.com/87025837/128196596-49a7a286-33c0-4592-8bf3-677e67d969cc.png)
![image](https://user-images.githubusercontent.com/87025837/128196631-bca74051-9e45-4e46-8e38-adc680eaaea8.png)

i've done every step by step that are in the readme.md, [npm i then npm run build on /client folder , and npm i then npm run start on /server folder] 
the website is working fine , but the only problem is its not receiving the data from the module's 
![image](https://user-images.githubusercontent.com/87025837/128197142-4af2c618-127e-42a7-bb6e-3cfff38e3a23.png)

any suggestion what i should try to resolve the issue? im guessing that its sending the data to the wrong endpoint, but im not sure which one to send it at

any response is appreciated

**Comment by Bobu5** [comment]
forgot to mention the OS Version, 
![image](https://user-images.githubusercontent.com/87025837/128605316-dfc53685-00e5-4319-924b-b33545622f19.png)

im using a modded Windows 10 21H1 that ghostspectre released [which removed some of "unused" thing, and im kinda suspicious that one of the "unused" thing that are getting removed is needed, im kinda curious which one tho

**Comment by matcool** [comment]
did you do all the steps in https://github.com/matcool/skyblock-jacob#collecting-the-data ?

**Comment by Bobu5** [comment]
> did you do all the steps in https://github.com/matcool/skyblock-jacob#collecting-the-data ?

hi Matcool thx fpr the reply, yes i alr done those step, all works fine until the /uploadjacobdata, no error or anything pop up on the chat, not even the `done` message from the server

**Comment by Bobu5** [comment]
and also may i ask where the `.json` file containing all the info the API needed is located? so i cam check if its issue with saving it to the json or something else

**Comment by kylewr** [comment]
> is located? so i cam check if its issue with saving it to the json or something else

if i remember correctly, i think data is stored in like a mysql db on the server side

**Comment by Bobu5** [comment]
> > is located? so i cam check if its issue with saving it to the json or something else
> 
> if i remember correctly, i think data is stored in like a mysql db on the server side

hi WindowsVistaisCool, i guess that explain why i cant upload any data to the server, at first i thought it was some problem with my OS , but i've even tried installing a windows [fresh install btw] and still the server somehow didnt receive/respond back after i send the command, i've tried changing something about the command so it told me that the command has ran and is trying to contact my server on localhost 
![image](https://user-images.githubusercontent.com/87025837/132134108-5a9dec65-be18-46ed-b38d-4e8becd3c7bc.png)

is there any other unmentioned step that i forgot to do? and also im sorry for my bad english and not knowing much about coding

**Comment by kylewr** [comment]
> > > is located? so i cam check if its issue with saving it to the json or something else
> > 
> > 
> > if i remember correctly, i think data is stored in like a mysql db on the server side
> 
> hi WindowsVistaisCool, i guess that explain why i cant upload any data to the server, at first i thought it was some problem with my OS , but i've even tried installing a windows [fresh install btw] and still the server somehow didnt receive/respond back after i send the command, i've tried changing something about the command so it told me that the command has ran and is trying to contact my server on localhost
> ![image](https://user-images.githubusercontent.com/87025837/132134108-5a9dec65-be18-46ed-b38d-4e8becd3c7bc.png)
> 
> is there any other unmentioned step that i forgot to do? and also im sorry for my bad english and not knowing much about coding

That's alright, I think @matcool's instructions are a bit unclear, but basically I created my own API (python) and had it write the data it received to a JSON file so my bot could parse. JSON isn't the greatest method of storage, as it can corrupt, so databases are the way to go. I modified the chattriggers module a bit to fix the url to my API and I put some try/catch there just for the sake of debugging. I didn't really do much client-side as I'm using a discord bot and just wanted to get the data. Sorry if this doesn't help a lot.

**Comment by Bobu5** [comment]
> > > > is located? so i cam check if its issue with saving it to the json or something else
> > > 
> > > 
> > > if i remember correctly, i think data is stored in like a mysql db on the server side
> > 
> > 
> > hi WindowsVistaisCool, i guess that explain why i cant upload any data to the server, at first i thought it was some problem with my OS , but i've even tried installing a windows [fresh install btw] and still the server somehow didnt receive/respond back after i send the command, i've tried changing something about the command so it told me that the command has ran and is trying to contact my server on localhost
> > ![image](https://user-images.githubusercontent.com/87025837/132134108-5a9dec65-be18-46ed-b38d-4e8becd3c7bc.png)
> > is there any other unmentioned step that i forgot to do? and also im sorry for my bad english and not knowing much about coding
> 
> That's alright, I think @matcool's instructions are a bit unclear, but basically I created my own API (python) and had it write the data it received to a JSON file so my bot could parse. JSON isn't the greatest method of storage, as it can corrupt, so databases are the way to go. I modified the chattriggers module a bit to fix the url to my API and I put some try/catch there just for the sake of debugging. I didn't really do much client-side as I'm using a discord bot and just wanted to get the data. Sorry if this doesn't help a lot.

thanks for the reply WindowsVistaisCool , thx for the reply and yes it does help alot ,it atleast helped me to understand that the cause of the problem is not my OS, but the way i installed it, as i thought the DB didnt received any of the data , imma try to atleast read it and see how i install and setup the database,

and also im sorry but is the bot opensource? i want to use it at my private server and learn things from the code, and dont worry i will still give u, matcool and the other contributor the credit u guys deserved

**Comment by matcool** [comment]
> > is located? so i cam check if its issue with saving it to the json or something else
> 
> if i remember correctly, i think data is stored in like a mysql db on the server side

The data is stored in a MongoDB database, https://github.com/matcool/skyblock-jacob/blob/master/server/index.js#L5 with this connection URI. The server relies on the db so if you dont have a mongodb instance nothing will work

**Comment by Bobu5** [comment]
> > > is located? so i cam check if its issue with saving it to the json or something else
> > 
> > 
> > if i remember correctly, i think data is stored in like a mysql db on the server side
> 
> The data is stored in a MongoDB database, https://github.com/matcool/skyblock-jacob/blob/master/server/index.js#L5 with this connection URI. The server relies on the db so if you dont have a mongodb instance nothing will work

hi matcool thx for the reply, im sorry but do u have any like suggestion on which youtube vids i should follow to set it up? ive heard a little bit of these mongodb things but still never touched them, once again thx and im sorry for wasting your time

**Comment by matcool** [comment]
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/

**Comment by Bobu5** [comment]
> https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/

thx, imma install and see if issue still persist

**Comment by kylewr** [comment]
> > > > > is located? so i cam check if its issue with saving it to the json or something else
> > > > 
> > > > 
> > > > if i remember correctly, i think data is stored in like a mysql db on the server side
> > > 
> > > 
> > > hi WindowsVistaisCool, i guess that explain why i cant upload any data to the server, at first i thought it was some problem with my OS , but i've even tried installing a windows [fresh install btw] and still the server somehow didnt receive/respond back after i send the command, i've tried changing something about the command so it told me that the command has ran and is trying to contact my server on localhost
> > > ![image](https://user-images.githubusercontent.com/87025837/132134108-5a9dec65-be18-46ed-b38d-4e8becd3c7bc.png)
> > > is there any other unmentioned step that i forgot to do? and also im sorry for my bad english and not knowing much about coding
> > 
> > 
> > That's alright, I think @matcool's instructions are a bit unclear, but basically I created my own API (python) and had it write the data it received to a JSON file so my bot could parse. JSON isn't the greatest method of storage, as it can corrupt, so databases are the way to go. I modified the chattriggers module a bit to fix the url to my API and I put some try/catch there just for the sake of debugging. I didn't really do much client-side as I'm using a discord bot and just wanted to get the data. Sorry if this doesn't help a lot.
> 
> thanks for the reply WindowsVistaisCool , thx for the reply and yes it does help alot ,it atleast helped me to understand that the cause of the problem is not my OS, but the way i installed it, as i thought the DB didnt received any of the data , imma try to atleast read it and see how i install and setup the database,
> 
> and also im sorry but is the bot opensource? i want to use it at my private server and learn things from the code, and dont worry i will still give u, matcool and the other contributor the credit u guys deserved

Sorry, it's not working atm, but my discord is rctngl#8676 (we should collaborate!)

**Comment by Bobu5** [comment]
> > > > > > is located? so i cam check if its issue with saving it to the json or something else
> > > > > 
> > > > > 
> > > > > if i remember correctly, i think data is stored in like a mysql db on the server side
> > > > 
> > > > 
> > > > hi WindowsVistaisCool, i guess that explain why i cant upload any data to the server, at first i thought it was some problem with my OS , but i've even tried installing a windows [fresh install btw] and still the server somehow didnt receive/respond back after i send the command, i've tried changing something about the command so it told me that the command has ran and is trying to contact my server on localhost
> > > > ![image](https://user-images.githubusercontent.com/87025837/132134108-5a9dec65-be18-46ed-b38d-4e8becd3c7bc.png)
> > > > is there any other unmentioned step that i forgot to do? and also im sorry for my bad english and not knowing much about coding
> > > 
> > > 
> > > That's alright, I think @matcool's instructions are a bit unclear, but basically I created my own API (python) and had it write the data it received to a JSON file so my bot could parse. JSON isn't the greatest method of storage, as it can corrupt, so databases are the way to go. I modified the chattriggers module a bit to fix the url to my API and I put some try/catch there just for the sake of debugging. I didn't really do much client-side as I'm using a discord bot and just wanted to get the data. Sorry if this doesn't help a lot.
> > 
> > 
> > thanks for the reply WindowsVistaisCool , thx for the reply and yes it does help alot ,it atleast helped me to understand that the cause of the problem is not my OS, but the way i installed it, as i thought the DB didnt received any of the data , imma try to atleast read it and see how i install and setup the database,
> > and also im sorry but is the bot opensource? i want to use it at my private server and learn things from the code, and dont worry i will still give u, matcool and the other contributor the credit u guys deserved
> 
> Sorry, it's not working atm, but my discord is rctngl#8676 (we should collaborate!)

hi WindowsVistaisCool , im so sorry but im literally garbage at coding, no knowledge at all, but im more than happy to give some input and maybe learn how to code things too from u, imma add u on discord , mine is RobusOfficial#7xx8

**Comment by Bobu5** [comment]
update: it works now! just forgot to install mongodb lmao

anyway thx for y'all for the help, thx matcool for making this, thx FluxCapacitor2 and UnrealValentin for contributing to this repo, and thx to WindowsVistaisCool for telling me about the db problem, imma close this issue now, bai

**Comment by marko-medvesek** [comment]
Im running this on Linux.
This is my situation [https://www.youtube.com/watch?v=O6pdmE6fdCE](https://www.youtube.com/watch?v=O6pdmE6fdCE)
Thanks in advance

**Comment by kylewr** [comment]
> Im running this on Linux. This is my situation https://www.youtube.com/watch?v=O6pdmE6fdCE Thanks in advance

I also didn't see your secret clearly, but it should match the one in the `.env` file on your server.
It appears you do not having the farming level requirement (10) and that's why contests don't show up.
You also forgot to run `/uploadjacobdata` which makes a request to the server.

**Comment by marko-medvesek** [comment]
> > Im running this on Linux. This is my situation https://www.youtube.com/watch?v=O6pdmE6fdCE Thanks in advance
> 
> I also didn't see your secret clearly, but it should match the one in the `.env` file on your server. It appears you do not having the farming level requirement (10) and that's why contests don't show up. You also forgot to run `/uploadjacobdata` which makes a request to the server.

Didn't help **:(** [https://youtu.be/9ydpN8mfQRo](https://youtu.be/9ydpN8mfQRo)
Thanks for quick reply,
_SlovenianGamer_

**Comment by kylewr** [comment]
> > > Im running this on Linux. This is my situation https://www.youtube.com/watch?v=O6pdmE6fdCE Thanks in advance
> > 
> > 
> > I also didn't see your secret clearly, but it should match the one in the `.env` file on your server. It appears you do not having the farming level requirement (10) and that's why contests don't show up. You also forgot to run `/uploadjacobdata` which makes a request to the server.
> 
> Didn't help **:(** https://youtu.be/9ydpN8mfQRo Thanks for quick reply, _SlovenianGamer_

Sorry about that, could you provide some feedback for me?
P.S. Your video is private & please open a new issue for this.

**Comment by marko-medvesek** [comment]
> > > > Im running this on Linux. This is my situation https://www.youtube.com/watch?v=O6pdmE6fdCE Thanks in advance
> > > 
> > > 
> > > I also didn't see your secret clearly, but it should match the one in the `.env` file on your server. It appears you do not having the farming level requirement (10) and that's why contests don't show up. You also forgot to run `/uploadjacobdata` which makes a request to the server.
> > 
> > 
> > Didn't help **:(** https://youtu.be/9ydpN8mfQRo Thanks for quick reply, _SlovenianGamer_
> 
> Sorry about that, could you provide some feedback for me? P.S. Your video is private & please open a new issue for this.

Ye, sorry about that :)
I forgot to press save button (use the same [link](https://youtu.be/9ydpN8mfQRo) )
:)

**Comment by kylewr** [comment]
> > > > > Im running this on Linux. This is my situation https://www.youtube.com/watch?v=O6pdmE6fdCE Thanks in advance
> > > > 
> > > > 
> > > > I also didn't see your secret clearly, but it should match the one in the `.env` file on your server. It appears you do not having the farming level requirement (10) and that's why contests don't show up. You also forgot to run `/uploadjacobdata` which makes a request to the server.
> > > 
> > > 
> > > Didn't help **:(** https://youtu.be/9ydpN8mfQRo Thanks for quick reply, _SlovenianGamer_
> > 
> > 
> > Sorry about that, could you provide some feedback for me? P.S. Your video is private & please open a new issue for this.
> 
> Ye, sorry about that :) I forgot to press save button (use the same [link](https://youtu.be/9ydpN8mfQRo) ) :)

Not sure what's wrong, seems like mongo isn't installed properly. Please open a new issue instead of commenting on this one.

**Comment by Bobu5** [comment]
> Im running this on Linux. This is my situation https://www.youtube.com/watch?v=O6pdmE6fdCE Thanks in advance

quick question, have u installed mongodb on the host (server) ? for me thats the source of the problem, not sure wbu tho, but yeah u might wanna give it a try

**Comment by kylewr** [comment]
> > Im running this on Linux. This is my situation https://www.youtube.com/watch?v=O6pdmE6fdCE Thanks in advance
> 
> quick question, have u installed mongodb on the host (server) ? for me thats the source of the problem, not sure wbu tho, but yeah u might wanna give it a try

Yeah it seems you have mongo (not sure that's mongoDB), but you should try to find docs on how to install mongo for ubuntu, because when you tried `apt` with mongoDB I saw it failed. Also please open a new issue for this
